// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "elte_playerctrl_video.h"

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl_video

IMPLEMENT_DYNCREATE(CElte_playerctrl_video, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl_video properties

/////////////////////////////////////////////////////////////////////////////
// CElte_playerctrl_video operations
