//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteHuawei.EventosIPCC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EventosTelefoniaSoap11", Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class EventosTelefoniaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback registraAtencionLlamadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraTiempoDuracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLlamadaProcesoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraRecepcionLlamadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLlamadaAbandonadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLlamadaColgadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLlamadaConcluidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambioEstadoAgenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLlamadaEsperaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EventosTelefoniaService() {
            this.Url = global::ClienteHuawei.Properties.Settings.Default.ClienteHuawei_EventosIPCC_EventosTelefoniaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event registraAtencionLlamadaCompletedEventHandler registraAtencionLlamadaCompleted;
        
        /// <remarks/>
        public event registraTiempoDuracionCompletedEventHandler registraTiempoDuracionCompleted;
        
        /// <remarks/>
        public event registraLlamadaProcesoCompletedEventHandler registraLlamadaProcesoCompleted;
        
        /// <remarks/>
        public event registraRecepcionLlamadaCompletedEventHandler registraRecepcionLlamadaCompleted;
        
        /// <remarks/>
        public event registraLlamadaAbandonadaCompletedEventHandler registraLlamadaAbandonadaCompleted;
        
        /// <remarks/>
        public event registraLlamadaColgadaCompletedEventHandler registraLlamadaColgadaCompleted;
        
        /// <remarks/>
        public event registraLlamadaConcluidaCompletedEventHandler registraLlamadaConcluidaCompleted;
        
        /// <remarks/>
        public event cambioEstadoAgenteCompletedEventHandler cambioEstadoAgenteCompleted;
        
        /// <remarks/>
        public event registraLlamadaEsperaCompletedEventHandler registraLlamadaEsperaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraAtencionLlamadaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraAtencionLlamadaResponse registraAtencionLlamada([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraAtencionLlamadaRequest registraAtencionLlamadaRequest) {
            object[] results = this.Invoke("registraAtencionLlamada", new object[] {
                        registraAtencionLlamadaRequest});
            return ((registraAtencionLlamadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraAtencionLlamadaAsync(registraAtencionLlamadaRequest registraAtencionLlamadaRequest) {
            this.registraAtencionLlamadaAsync(registraAtencionLlamadaRequest, null);
        }
        
        /// <remarks/>
        public void registraAtencionLlamadaAsync(registraAtencionLlamadaRequest registraAtencionLlamadaRequest, object userState) {
            if ((this.registraAtencionLlamadaOperationCompleted == null)) {
                this.registraAtencionLlamadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraAtencionLlamadaOperationCompleted);
            }
            this.InvokeAsync("registraAtencionLlamada", new object[] {
                        registraAtencionLlamadaRequest}, this.registraAtencionLlamadaOperationCompleted, userState);
        }
        
        private void OnregistraAtencionLlamadaOperationCompleted(object arg) {
            if ((this.registraAtencionLlamadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraAtencionLlamadaCompleted(this, new registraAtencionLlamadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraTiempoDuracionResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraTiempoDuracionResponse registraTiempoDuracion([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraTiempoDuracionRequest registraTiempoDuracionRequest) {
            object[] results = this.Invoke("registraTiempoDuracion", new object[] {
                        registraTiempoDuracionRequest});
            return ((registraTiempoDuracionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraTiempoDuracionAsync(registraTiempoDuracionRequest registraTiempoDuracionRequest) {
            this.registraTiempoDuracionAsync(registraTiempoDuracionRequest, null);
        }
        
        /// <remarks/>
        public void registraTiempoDuracionAsync(registraTiempoDuracionRequest registraTiempoDuracionRequest, object userState) {
            if ((this.registraTiempoDuracionOperationCompleted == null)) {
                this.registraTiempoDuracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraTiempoDuracionOperationCompleted);
            }
            this.InvokeAsync("registraTiempoDuracion", new object[] {
                        registraTiempoDuracionRequest}, this.registraTiempoDuracionOperationCompleted, userState);
        }
        
        private void OnregistraTiempoDuracionOperationCompleted(object arg) {
            if ((this.registraTiempoDuracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraTiempoDuracionCompleted(this, new registraTiempoDuracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraLlamadaProcesoResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraLlamadaProcesoResponse registraLlamadaProceso([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraLlamadaProcesoRequest registraLlamadaProcesoRequest) {
            object[] results = this.Invoke("registraLlamadaProceso", new object[] {
                        registraLlamadaProcesoRequest});
            return ((registraLlamadaProcesoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraLlamadaProcesoAsync(registraLlamadaProcesoRequest registraLlamadaProcesoRequest) {
            this.registraLlamadaProcesoAsync(registraLlamadaProcesoRequest, null);
        }
        
        /// <remarks/>
        public void registraLlamadaProcesoAsync(registraLlamadaProcesoRequest registraLlamadaProcesoRequest, object userState) {
            if ((this.registraLlamadaProcesoOperationCompleted == null)) {
                this.registraLlamadaProcesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLlamadaProcesoOperationCompleted);
            }
            this.InvokeAsync("registraLlamadaProceso", new object[] {
                        registraLlamadaProcesoRequest}, this.registraLlamadaProcesoOperationCompleted, userState);
        }
        
        private void OnregistraLlamadaProcesoOperationCompleted(object arg) {
            if ((this.registraLlamadaProcesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLlamadaProcesoCompleted(this, new registraLlamadaProcesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraRecepcionLlamadaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraRecepcionLlamadaResponse registraRecepcionLlamada([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraRecepcionLlamadaRequest registraRecepcionLlamadaRequest) {
            object[] results = this.Invoke("registraRecepcionLlamada", new object[] {
                        registraRecepcionLlamadaRequest});
            return ((registraRecepcionLlamadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraRecepcionLlamadaAsync(registraRecepcionLlamadaRequest registraRecepcionLlamadaRequest) {
            this.registraRecepcionLlamadaAsync(registraRecepcionLlamadaRequest, null);
        }
        
        /// <remarks/>
        public void registraRecepcionLlamadaAsync(registraRecepcionLlamadaRequest registraRecepcionLlamadaRequest, object userState) {
            if ((this.registraRecepcionLlamadaOperationCompleted == null)) {
                this.registraRecepcionLlamadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraRecepcionLlamadaOperationCompleted);
            }
            this.InvokeAsync("registraRecepcionLlamada", new object[] {
                        registraRecepcionLlamadaRequest}, this.registraRecepcionLlamadaOperationCompleted, userState);
        }
        
        private void OnregistraRecepcionLlamadaOperationCompleted(object arg) {
            if ((this.registraRecepcionLlamadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraRecepcionLlamadaCompleted(this, new registraRecepcionLlamadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraLlamadaAbandonadaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraLlamadaAbandonadaResponse registraLlamadaAbandonada([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraLlamadaAbandonadaRequest registraLlamadaAbandonadaRequest) {
            object[] results = this.Invoke("registraLlamadaAbandonada", new object[] {
                        registraLlamadaAbandonadaRequest});
            return ((registraLlamadaAbandonadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraLlamadaAbandonadaAsync(registraLlamadaAbandonadaRequest registraLlamadaAbandonadaRequest) {
            this.registraLlamadaAbandonadaAsync(registraLlamadaAbandonadaRequest, null);
        }
        
        /// <remarks/>
        public void registraLlamadaAbandonadaAsync(registraLlamadaAbandonadaRequest registraLlamadaAbandonadaRequest, object userState) {
            if ((this.registraLlamadaAbandonadaOperationCompleted == null)) {
                this.registraLlamadaAbandonadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLlamadaAbandonadaOperationCompleted);
            }
            this.InvokeAsync("registraLlamadaAbandonada", new object[] {
                        registraLlamadaAbandonadaRequest}, this.registraLlamadaAbandonadaOperationCompleted, userState);
        }
        
        private void OnregistraLlamadaAbandonadaOperationCompleted(object arg) {
            if ((this.registraLlamadaAbandonadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLlamadaAbandonadaCompleted(this, new registraLlamadaAbandonadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraLlamadaColgadaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraLlamadaColgadaResponse registraLlamadaColgada([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraLlamadaColgadaRequest registraLlamadaColgadaRequest) {
            object[] results = this.Invoke("registraLlamadaColgada", new object[] {
                        registraLlamadaColgadaRequest});
            return ((registraLlamadaColgadaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraLlamadaColgadaAsync(registraLlamadaColgadaRequest registraLlamadaColgadaRequest) {
            this.registraLlamadaColgadaAsync(registraLlamadaColgadaRequest, null);
        }
        
        /// <remarks/>
        public void registraLlamadaColgadaAsync(registraLlamadaColgadaRequest registraLlamadaColgadaRequest, object userState) {
            if ((this.registraLlamadaColgadaOperationCompleted == null)) {
                this.registraLlamadaColgadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLlamadaColgadaOperationCompleted);
            }
            this.InvokeAsync("registraLlamadaColgada", new object[] {
                        registraLlamadaColgadaRequest}, this.registraLlamadaColgadaOperationCompleted, userState);
        }
        
        private void OnregistraLlamadaColgadaOperationCompleted(object arg) {
            if ((this.registraLlamadaColgadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLlamadaColgadaCompleted(this, new registraLlamadaColgadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraLlamadaConcluidaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraLlamadaConcluidaResponse registraLlamadaConcluida([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraLlamadaConcluidaRequest registraLlamadaConcluidaRequest) {
            object[] results = this.Invoke("registraLlamadaConcluida", new object[] {
                        registraLlamadaConcluidaRequest});
            return ((registraLlamadaConcluidaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraLlamadaConcluidaAsync(registraLlamadaConcluidaRequest registraLlamadaConcluidaRequest) {
            this.registraLlamadaConcluidaAsync(registraLlamadaConcluidaRequest, null);
        }
        
        /// <remarks/>
        public void registraLlamadaConcluidaAsync(registraLlamadaConcluidaRequest registraLlamadaConcluidaRequest, object userState) {
            if ((this.registraLlamadaConcluidaOperationCompleted == null)) {
                this.registraLlamadaConcluidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLlamadaConcluidaOperationCompleted);
            }
            this.InvokeAsync("registraLlamadaConcluida", new object[] {
                        registraLlamadaConcluidaRequest}, this.registraLlamadaConcluidaOperationCompleted, userState);
        }
        
        private void OnregistraLlamadaConcluidaOperationCompleted(object arg) {
            if ((this.registraLlamadaConcluidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLlamadaConcluidaCompleted(this, new registraLlamadaConcluidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("cambioEstadoAgenteResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public cambioEstadoAgenteResponse cambioEstadoAgente([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] cambioEstadoAgenteRequest cambioEstadoAgenteRequest) {
            object[] results = this.Invoke("cambioEstadoAgente", new object[] {
                        cambioEstadoAgenteRequest});
            return ((cambioEstadoAgenteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cambioEstadoAgenteAsync(cambioEstadoAgenteRequest cambioEstadoAgenteRequest) {
            this.cambioEstadoAgenteAsync(cambioEstadoAgenteRequest, null);
        }
        
        /// <remarks/>
        public void cambioEstadoAgenteAsync(cambioEstadoAgenteRequest cambioEstadoAgenteRequest, object userState) {
            if ((this.cambioEstadoAgenteOperationCompleted == null)) {
                this.cambioEstadoAgenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambioEstadoAgenteOperationCompleted);
            }
            this.InvokeAsync("cambioEstadoAgente", new object[] {
                        cambioEstadoAgenteRequest}, this.cambioEstadoAgenteOperationCompleted, userState);
        }
        
        private void OncambioEstadoAgenteOperationCompleted(object arg) {
            if ((this.cambioEstadoAgenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambioEstadoAgenteCompleted(this, new cambioEstadoAgenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("registraLlamadaEsperaResponse", Namespace="http://integracion.promad.esb/telefonia/eventos")]
        public registraLlamadaEsperaResponse registraLlamadaEspera([System.Xml.Serialization.XmlElementAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")] registraLlamadaEsperaRequest registraLlamadaEsperaRequest) {
            object[] results = this.Invoke("registraLlamadaEspera", new object[] {
                        registraLlamadaEsperaRequest});
            return ((registraLlamadaEsperaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void registraLlamadaEsperaAsync(registraLlamadaEsperaRequest registraLlamadaEsperaRequest) {
            this.registraLlamadaEsperaAsync(registraLlamadaEsperaRequest, null);
        }
        
        /// <remarks/>
        public void registraLlamadaEsperaAsync(registraLlamadaEsperaRequest registraLlamadaEsperaRequest, object userState) {
            if ((this.registraLlamadaEsperaOperationCompleted == null)) {
                this.registraLlamadaEsperaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLlamadaEsperaOperationCompleted);
            }
            this.InvokeAsync("registraLlamadaEspera", new object[] {
                        registraLlamadaEsperaRequest}, this.registraLlamadaEsperaOperationCompleted, userState);
        }
        
        private void OnregistraLlamadaEsperaOperationCompleted(object arg) {
            if ((this.registraLlamadaEsperaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLlamadaEsperaCompleted(this, new registraLlamadaEsperaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraAtencionLlamadaRequest {
        
        private asociacionAgente asociacionAgenteField;
        
        private string uniqueIdField;
        
        private string callerIdField;
        
        private string canalField;
        
        private string nombreArchivoField;
        
        private string urlArchivoField;
        
        private string coordXField;
        
        private string coordYField;
        
        /// <comentarios/>
        public asociacionAgente asociacionAgente {
            get {
                return this.asociacionAgenteField;
            }
            set {
                this.asociacionAgenteField = value;
            }
        }
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <comentarios/>
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <comentarios/>
        public string urlArchivo {
            get {
                return this.urlArchivoField;
            }
            set {
                this.urlArchivoField = value;
            }
        }
        
        /// <comentarios/>
        public string coordX {
            get {
                return this.coordXField;
            }
            set {
                this.coordXField = value;
            }
        }
        
        /// <comentarios/>
        public string coordY {
            get {
                return this.coordYField;
            }
            set {
                this.coordYField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracion.promad.esb/telefonia/esquemas")]
    public partial class asociacionAgente {
        
        private string numeroAgenteField;
        
        private string numeroExtensionField;
        
        private string ipField;
        
        /// <comentarios/>
        public string numeroAgente {
            get {
                return this.numeroAgenteField;
            }
            set {
                this.numeroAgenteField = value;
            }
        }
        
        /// <comentarios/>
        public string numeroExtension {
            get {
                return this.numeroExtensionField;
            }
            set {
                this.numeroExtensionField = value;
            }
        }
        
        /// <comentarios/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraAtencionLlamadaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraTiempoDuracionRequest {
        
        private asociacionAgente asociacionAgenteField;
        
        private string uniqueIdField;
        
        private string tiempoDuracionField;
        
        /// <comentarios/>
        public asociacionAgente asociacionAgente {
            get {
                return this.asociacionAgenteField;
            }
            set {
                this.asociacionAgenteField = value;
            }
        }
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tiempoDuracion {
            get {
                return this.tiempoDuracionField;
            }
            set {
                this.tiempoDuracionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraTiempoDuracionResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaProcesoRequest {
        
        private string lineaField;
        
        private string extensionField;
        
        private string callerIdField;
        
        private string uniqueIdField;
        
        private System.DateTime fechaHoraField;
        
        private EnumClaseLlamada claseLlamadaField;
        
        /// <comentarios/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <comentarios/>
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <comentarios/>
        public EnumClaseLlamada claseLlamada {
            get {
                return this.claseLlamadaField;
            }
            set {
                this.claseLlamadaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public enum EnumClaseLlamada {
        
        /// <comentarios/>
        IN,
        
        /// <comentarios/>
        OUT,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaProcesoResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraRecepcionLlamadaRequest {
        
        private asociacionAgente asociacionAgenteField;
        
        private string uniqueIdField;
        
        private string callerIdField;
        
        private string canalField;
        
        private string coordXField;
        
        private string coordYField;
        
        /// <comentarios/>
        public asociacionAgente asociacionAgente {
            get {
                return this.asociacionAgenteField;
            }
            set {
                this.asociacionAgenteField = value;
            }
        }
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <comentarios/>
        public string coordX {
            get {
                return this.coordXField;
            }
            set {
                this.coordXField = value;
            }
        }
        
        /// <comentarios/>
        public string coordY {
            get {
                return this.coordYField;
            }
            set {
                this.coordYField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraRecepcionLlamadaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        private long uniqueIDField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public long uniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaAbandonadaRequest {
        
        private string idTelefoniaField;
        
        private string callerIdField;
        
        private string tiempoAbandonoField;
        
        /// <comentarios/>
        public string idTelefonia {
            get {
                return this.idTelefoniaField;
            }
            set {
                this.idTelefoniaField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tiempoAbandono {
            get {
                return this.tiempoAbandonoField;
            }
            set {
                this.tiempoAbandonoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaAbandonadaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaColgadaRequest {
        
        private string idTelefoniaField;
        
        private string callerIdField;
        
        private string tiempoAbandonoField;
        
        /// <comentarios/>
        public string idTelefonia {
            get {
                return this.idTelefoniaField;
            }
            set {
                this.idTelefoniaField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tiempoAbandono {
            get {
                return this.tiempoAbandonoField;
            }
            set {
                this.tiempoAbandonoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaColgadaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaConcluidaRequest {
        
        private string uniqueIdField;
        
        private System.DateTime fechaHoraField;
        
        private string tiempoDuracionField;
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tiempoDuracion {
            get {
                return this.tiempoDuracionField;
            }
            set {
                this.tiempoDuracionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaConcluidaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class cambioEstadoAgenteRequest {
        
        private asociacionAgente asociacionAgenteField;
        
        private EnumDisponibilidad disponibilidadField;
        
        /// <comentarios/>
        public asociacionAgente asociacionAgente {
            get {
                return this.asociacionAgenteField;
            }
            set {
                this.asociacionAgenteField = value;
            }
        }
        
        /// <comentarios/>
        public EnumDisponibilidad disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                this.disponibilidadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public enum EnumDisponibilidad {
        
        /// <comentarios/>
        DISPONIBLE,
        
        /// <comentarios/>
        NO_DISPONIBLE,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class cambioEstadoAgenteResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaEsperaRequest {
        
        private string idTelefoniaField;
        
        private string callerIdField;
        
        private string uniqueIdField;
        
        /// <comentarios/>
        public string idTelefonia {
            get {
                return this.idTelefoniaField;
            }
            set {
                this.idTelefoniaField = value;
            }
        }
        
        /// <comentarios/>
        public string callerId {
            get {
                return this.callerIdField;
            }
            set {
                this.callerIdField = value;
            }
        }
        
        /// <comentarios/>
        public string uniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://integracion.promad.esb/telefonia/eventos")]
    public partial class registraLlamadaEsperaResponse {
        
        private string codigoErrorField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraAtencionLlamadaCompletedEventHandler(object sender, registraAtencionLlamadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraAtencionLlamadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraAtencionLlamadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraAtencionLlamadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraAtencionLlamadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraTiempoDuracionCompletedEventHandler(object sender, registraTiempoDuracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraTiempoDuracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraTiempoDuracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraTiempoDuracionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraTiempoDuracionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraLlamadaProcesoCompletedEventHandler(object sender, registraLlamadaProcesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLlamadaProcesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLlamadaProcesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraLlamadaProcesoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraLlamadaProcesoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraRecepcionLlamadaCompletedEventHandler(object sender, registraRecepcionLlamadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraRecepcionLlamadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraRecepcionLlamadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraRecepcionLlamadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraRecepcionLlamadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraLlamadaAbandonadaCompletedEventHandler(object sender, registraLlamadaAbandonadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLlamadaAbandonadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLlamadaAbandonadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraLlamadaAbandonadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraLlamadaAbandonadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraLlamadaColgadaCompletedEventHandler(object sender, registraLlamadaColgadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLlamadaColgadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLlamadaColgadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraLlamadaColgadaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraLlamadaColgadaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraLlamadaConcluidaCompletedEventHandler(object sender, registraLlamadaConcluidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLlamadaConcluidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLlamadaConcluidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraLlamadaConcluidaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraLlamadaConcluidaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cambioEstadoAgenteCompletedEventHandler(object sender, cambioEstadoAgenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambioEstadoAgenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambioEstadoAgenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cambioEstadoAgenteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cambioEstadoAgenteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void registraLlamadaEsperaCompletedEventHandler(object sender, registraLlamadaEsperaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLlamadaEsperaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLlamadaEsperaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registraLlamadaEsperaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registraLlamadaEsperaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591